import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        serif: ['Merriweather', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "headline": ["Playfair Display", "serif"],
        "body": ["Source Serif 4", "serif"],
        "label": ["IBM Plex Mono", "monospace"],
        "serif-body": ["Source Serif 4", "serif"]
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#111318",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#b6c4ff",
          foreground: "hsl(var(--primary-foreground))",
          container: "#0057ff",
          fixed: "#dce1ff",
          "fixed-dim": "#b6c4ff",
        },
        secondary: {
          DEFAULT: "#ffb955",
          foreground: "hsl(var(--secondary-foreground))",
          container: "#dc9100",
          fixed: "#ffddb4",
          "fixed-dim": "#ffb955",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        highlight: {
          DEFAULT: "hsl(var(--highlight))",
          foreground: "hsl(var(--highlight-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "on-tertiary-fixed": "#002113",
        "inverse-primary": "#004ee7",
        "inverse-on-surface": "#2f3035",
        "surface-variant": "#333539",
        "on-primary-fixed": "#001550",
        "primary-container": "#0057ff",
        "surface-dim": "#111318",
        "on-tertiary-fixed-variant": "#005234",
        "tertiary-fixed-dim": "#17e29a",
        "on-primary-fixed-variant": "#003ab2",
        "surface": "#111318",
        "tertiary-fixed": "#4dffb4",
        "inverse-surface": "#e2e2e8",
        "secondary-fixed": "#ffddb4",
        "surface-bright": "#37393e",
        "error-container": "#93000a",
        "on-primary-container": "#e5e8ff",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#00784f",
        "outline": "#8d90a2",
        "secondary-container": "#dc9100",
        "on-tertiary": "#003823",
        "on-secondary": "#452b00",
        "tertiary": "#17e29a",
        "surface-container-lowest": "#0c0e12",
        "on-surface": "#e2e2e8",
        "on-primary": "#00277f",
        "surface-container": "#1e2024",
        "on-tertiary-container": "#8fffc6",
        "on-secondary-container": "#4f3100",
        "surface-container-high": "#282a2e",
        "outline-variant": "#434656",
        "on-surface-variant": "#c3c5d9",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#633f00",
        "on-secondary-fixed": "#291800",
        "surface-tint": "#b6c4ff",
        "surface-container-low": "#1a1c20",
        "surface-container-highest": "#333539",
        "on-background": "#e2e2e8"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
